### ISSUE TITLE
Country Charts Information Not Descriptive

### ISSUE THREAD

**Issue by MilosBijelic** [sashaobucina/coronatracker#1]
Metrics not clearly defined for countries

1) Total cases: make sense 
2) New cases: is this new cases today?
3) Percent change: is this day over day? Today vs. Yesterday? 
4) Max number of cases: is this the largest number of new cases in a single day?
5) Days since peak: makes sense
6) percent below peak: is this the discrepancy between the number of cases today and the max number of cases in a single day (metric 4) as: 
(max cases - todays cases)/max cases ?

**Comment by sashaobucina** [comment]
- New Cases: All new reported cases as of the previous day (single day jump)
- Percent Change: Yes, this a day by day percent change calculation
- Max # of Cases: Yes, it's the highest number of new cases in a  single day; will change to "Max # of **New** Cases"
- Percent Below Peak: Yes, its the same methodology

These make more sense when searching for the country, since the summary card show is prefaced by a title indicating it is a daily report, which implies single day metrics where applicable (aka new cases and percent change).

For tidiness of table rows, will keep the same metric titles, but will add a FAQ card that explains metrics more clearly.
