### ISSUE TITLE
Metrics given are not relevant to growth

### ISSUE THREAD

**Issue by MilosBijelic** [sashaobucina/coronatracker#2]
- add a toggle for abesolute and relative numbers for new cases, % change etc.

Given the exponential nature of the disease spread numbers with respect to the base population are a lot more insightful than abesolute values. 50 new cases in a country with 5 million people means a lot more than 50 new cases in a country with 500 million people

**Comment by sashaobucina** [comment]
Currently this is outside the scope of the web app since up-to-date information of country populations would need to be aggregated and kept in line with valid countries that John Hopkins CSSE keeps track of (could be naming discrepancies that would need to be solved), but could be potentially re-opened later on.
